# Generated by Django 2.2.11 on 2020-03-26 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img_alt',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='img_url',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
